// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Context;

#nullable disable

namespace DbTravel.Model.Migrations
{
    [DbContext(typeof(DbTravelContext))]
    [Migration("20231121092545_iniaast")]
    partial class iniaast
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DbShop.Model.Models.BaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("IdNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("idNguoiDung");

                    b.Property<DateTime?>("NgayDang")
                        .HasColumnType("date")
                        .HasColumnName("ngayDang");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text")
                        .HasColumnName("noiDung");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tieuDe");

                    b.HasKey("Id");

                    b.HasIndex("IdNguoiDung");

                    b.ToTable("BaiViet", (string)null);
                });

            modelBuilder.Entity("DbShop.Model.Models.ChiTietTour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnhTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdTourDuLich")
                        .HasColumnType("int")
                        .HasColumnName("idTourDuLich");

                    b.Property<string>("KhoiHanh")
                        .HasColumnType("text")
                        .HasColumnName("khoiHanh");

                    b.Property<string>("LichTrinh")
                        .HasColumnType("text")
                        .HasColumnName("lichTrinh");

                    b.Property<string>("PhuongTien")
                        .HasColumnType("text")
                        .HasColumnName("phuongTien");

                    b.Property<string>("ThoiGian")
                        .HasColumnType("text")
                        .HasColumnName("thoiGian");

                    b.HasKey("Id");

                    b.HasIndex("IdTourDuLich");

                    b.ToTable("ChiTietTour", (string)null);
                });

            modelBuilder.Entity("DbShop.Model.Models.DatTour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("IdNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("idNguoiDung");

                    b.Property<int?>("IdTourDuLich")
                        .HasColumnType("int")
                        .HasColumnName("idTourDuLich");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("date")
                        .HasColumnName("ngayDat");

                    b.Property<int?>("SoNguoi")
                        .HasColumnType("int")
                        .HasColumnName("soNguoi");

                    b.HasKey("Id");

                    b.HasIndex("IdNguoiDung");

                    b.HasIndex("IdTourDuLich");

                    b.ToTable("DatTour", (string)null);
                });

            modelBuilder.Entity("DbShop.Model.Models.DiaDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("hinhAnh");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("moTa");

                    b.Property<string>("TenDiaDiem")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tenDiaDiem");

                    b.HasKey("Id");

                    b.ToTable("DiaDiem", (string)null);
                });

            modelBuilder.Entity("DbShop.Model.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Avartar")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("hoTen");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("isAdmin");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("matKhau");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("soDienThoai");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tenDangNhap");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("DbShop.Model.Models.TourDuLich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnhTour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("gia");

                    b.Property<int?>("IdDiaDiem")
                        .HasColumnType("int")
                        .HasColumnName("idDiaDiem");

                    b.Property<string>("KhuVuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("moTa");

                    b.Property<string>("TenTour")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tenTour");

                    b.HasKey("Id");

                    b.HasIndex("IdDiaDiem");

                    b.ToTable("TourDuLich", (string)null);
                });

            modelBuilder.Entity("DbShop.Model.Models.BaiViet", b =>
                {
                    b.HasOne("DbShop.Model.Models.NguoiDung", "IdNguoiDungNavigation")
                        .WithMany("BaiViets")
                        .HasForeignKey("IdNguoiDung")
                        .HasConstraintName("FK__BaiViet__idNguoi__2B3F6F97");

                    b.Navigation("IdNguoiDungNavigation");
                });

            modelBuilder.Entity("DbShop.Model.Models.ChiTietTour", b =>
                {
                    b.HasOne("DbShop.Model.Models.TourDuLich", "IdTourDuLichNavigation")
                        .WithMany("ChiTietTours")
                        .HasForeignKey("IdTourDuLich")
                        .HasConstraintName("FK__ChiTietTo__idTou__31EC6D26");

                    b.Navigation("IdTourDuLichNavigation");
                });

            modelBuilder.Entity("DbShop.Model.Models.DatTour", b =>
                {
                    b.HasOne("DbShop.Model.Models.NguoiDung", "IdNguoiDungNavigation")
                        .WithMany("DatTours")
                        .HasForeignKey("IdNguoiDung")
                        .HasConstraintName("FK__DatTour__idNguoi__2E1BDC42");

                    b.HasOne("DbShop.Model.Models.TourDuLich", "IdTourDuLichNavigation")
                        .WithMany("DatTours")
                        .HasForeignKey("IdTourDuLich")
                        .HasConstraintName("FK__DatTour__idTourD__2F10007B");

                    b.Navigation("IdNguoiDungNavigation");

                    b.Navigation("IdTourDuLichNavigation");
                });

            modelBuilder.Entity("DbShop.Model.Models.TourDuLich", b =>
                {
                    b.HasOne("DbShop.Model.Models.DiaDiem", "IdDiaDiemNavigation")
                        .WithMany("TourDuLiches")
                        .HasForeignKey("IdDiaDiem")
                        .HasConstraintName("FK__TourDuLic__idDia__267ABA7A");

                    b.Navigation("IdDiaDiemNavigation");
                });

            modelBuilder.Entity("DbShop.Model.Models.DiaDiem", b =>
                {
                    b.Navigation("TourDuLiches");
                });

            modelBuilder.Entity("DbShop.Model.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiViets");

                    b.Navigation("DatTours");
                });

            modelBuilder.Entity("DbShop.Model.Models.TourDuLich", b =>
                {
                    b.Navigation("ChiTietTours");

                    b.Navigation("DatTours");
                });
#pragma warning restore 612, 618
        }
    }
}
